import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { MotionDiv } from "~/components";
import { Header } from "~/components/header";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex min-h-screen flex-col items-center justify-center bg-dark">
        <section id="me">
          <div className="flex h-screen w-screen flex-col items-center justify-center  space-y-8 overflow-hidden text-center">
            <MotionDiv
              initial={{ opacity: 0 }}
              animate={{
                opacity: [0.1, 0.2, 0.4, 0.8, 0.1, 1],
                scale: [1, 2, 2, 3, 1],
                borderRadius: ["20%", "20%", "50%", "80%", "20%"],
              }}
              transition={{
                duration: 2.5,
              }}
              className="relative flex items-center justify-center"
            >
              <div className="absolute mt-52 h-[200px] w-[200px] animate-ping rounded-full border border-[#333333]" />
              <div className="absolute mt-52 h-[300px] w-[300px] rounded-full border border-[#333333]" />
              <div className="absolute mt-52 h-[500px] w-[500px] rounded-full border border-[#333333]" />
              <div className="absolute mt-52 h-[650px] w-[650px] animate-pulse rounded-full border border-secondary" />
              <div className="absolute mt-52 h-[800px] w-[800px] rounded-full border border-[#333333]" />
            </MotionDiv>

            <Image
              src="https://avatars.githubusercontent.com/u/56320155?v=4"
              priority
              height={144}
              width={144}
              alt="Profile picture"
              className="relative mx-auto h-36 w-36 rounded-full"
            />
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
