import { type NextPage } from "next";
import Head from "next/head";
import { motion } from "framer-motion";

const MotionDiv = motion.div;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <section id="me">
          <MotionDiv
            initial={{ opacity: 0 }}
            animate={{
              opacity: [0.1, 0.2, 0.4, 0.8, 0.1, 1],
              scale: [1, 2, 2, 3, 1],
              borderRadius: ["20%", "20%", "50%", "80%", "20%"],
            }}
            transition={{
              duration: 2.5,
            }}
            className="relative flex items-center justify-center"
          >
            <div className="absolute mt-52 h-[200px] w-[200px] animate-ping rounded-full border border-[#333333]" />
            <div className="absolute mt-52 h-[300px] w-[300px] rounded-full border border-[#333333]" />
            <div className="absolute mt-52 h-[500px] w-[500px] rounded-full border border-[#333333]" />
            <div className="border-accent-500 absolute mt-52 h-[650px] w-[650px] animate-pulse rounded-full border" />
            <div className="absolute mt-52 h-[800px] w-[800px] rounded-full border border-[#333333]" />
          </MotionDiv>
        </section>
      </main>
    </>
  );
};

export default Home;
